[profile.default]
src = "contracts"
out = "artifacts"
libs = ["lib", "node_modules"]
ignored_error_codes = [5574, 6321]
fs_permissions = [{ access = "read-write", path = "script/issuers.json"}]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
