@startuml sequence
actor       Artist       as artist
entity Frontend as front
entity BlockchainNode as bnode
participant GenTKProject as gentkp
participant GenTK as gentk
database    DecentralizedMediaCluster    as decMedCluster

group Project creation
artist -> front : createProject()
front -> decMedCluster : uploadProject()
front -> decMedCluster : uploadProjectMetadata()
front -> bnode : send_tx()
bnode -> gentkp : createProject()
end

@enduml
