@startuml sequence
entity    Backend    as backend
entity WalletManager as walletM
entity BlockchainNode as bnode
participant GenTK as gentk
queue       RenderingPipeline as render_pipe
database    DecentralizedMediaCluster    as decMedCluster



group Token reaveal
backend -> render_pipe: generate_images()
render_pipe -> decMedCluster: generate_images()
backend -> decMedCluster: upload_revealed_metadata()
backend -> walletM: assign_metadata()
walletM -> bnode: send_tx()
bnode -> gentk: assign_metadata()
end
@enduml
