name: test

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: install dependencies 
        run: npm ci

      - name: check formatting
        run: npx prettier --check 'src/**/*.sol' 'test/**/*.sol' 'script/**/*.sol'

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run tests
        shell: bash
        run: |
          forge test
        id: test

      - name: Upload Selectors to Openchain.xyz
        run: |
          forge selectors upload --all

      - name: "Generate coverage report"
        run: "forge coverage --report lcov"

      - name: "Upload coverage report to Codecov"
        uses: "codecov/codecov-action@v3"
        with:
          files: "./lcov.info"
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: "Add coverage summary"
        run: |
          echo "## Coverage result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Uploaded to Codecov" >> $GITHUB_STEP_SUMMARY
      - name: Deploy script
        run: |
          forge script script/Deploy.s.sol
