name: test

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  push:
    branches:
      - main
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v2
      - name: Install dev dependencies
        run: npm install

      - name: check formatting
        run: npm run prettier:check

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run tests
        shell: bash
        env:
          COIN_MARKET_CAP_API_KEY: ${{ secrets.COIN_MARKET_CAP_API_KEY }}
          DEPLOYER_PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          SIGNER_PRIVATE_KEY: ${{ secrets.SIGNER_PRIVATE_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
          ALICE_ADDRESS: ${{ env.ALICE_ADDRESS }}
          BOB_ADDRESS: ${{ env.BOB_ADDRESS }}
          TREASURY_ADDRESS: ${{ env.TREASURY_ADDRESS }}
        run: |
          npm test
        id: test
